feat: mutants - file and exit code handling, readme structure
- update readme files
- check exit codes
- check that files exist before accessing them, otherwise exit
- remove shell scripts folder since it was only used in 1 place
- update actions versions used

diff --git a/mutation-testing/check-packages-and-shards/action.yml b/mutation-testing/check-packages-and-shards/action.yml
--- a/mutation-testing/check-packages-and-shards/action.yml
+++ b/mutation-testing/check-packages-and-shards/action.yml
@@ -92,6 +92,11 @@ runs:
 
         # Make a file containing all the mutants for the differences in the PR and a folder to split them into big and small packages
         cargo mutants --in-diff git.diff --list > all_mutants.txt
+        if [ $? -ne 0 ]; then 
+          echo "Error retrieving the list of mutants!"
+          exit $?
+        fi
+
         mkdir -p mutants_by_packages
 
         # Check that the file exists before performing actions on it
diff --git a/mutation-testing/pr-differences/action.yml b/mutation-testing/pr-differences/action.yml
--- a/mutation-testing/pr-differences/action.yml
+++ b/mutation-testing/pr-differences/action.yml
@@ -1,4 +1,8 @@
 name: PR Differences Mutants
+description: "Runs mutants corresponding to its given inputs and uploads the outcomes to artifacts"
+branding:
+  icon: "users"
+  color: "gray-dark"
 
 inputs:
   shard:
@@ -31,25 +35,6 @@ runs:
       run: |
         git diff origin/${{ github.base_ref }}.. > git.diff
 
-    # Checkout the actions code
-    - name: Checkout actions repo
-      id: git_checkout_actions
-      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-      with:
-        repository: stacks-network/actions
-        ref: feat/mutation-testing
-        path: ./actions-repo
-
-    - name: Copy git diff
-      id: copy_git_diff
-      shell: bash
-      run: |
-        if [ ! -s git.diff ]; then
-          echo "Diff file (git.diff) is missing!"
-        fi
-
-        mv git.diff ./actions-repo/mutation-testing/shell-scripts/
-
     - uses: taiki-e/install-action@ac89944b5b150d78567ab6c02badfbe48b0b55aa # v2.20.16
       name: Install cargo-mutants
       id: install_cargo_mutants
@@ -59,8 +44,42 @@ runs:
     - name: Update git diff
       id: update_git_diff
       shell: bash
-      run: ./remove-deleted-file-lines.sh
-      working-directory: actions-repo/mutation-testing/shell-scripts
+      run: |
+        input_file="git.diff"
+        temp_file="temp_diff_file.diff"
+
+        # Check if the commands exist on the host
+        for cmd in tac awk sed; do
+          command -v "${cmd}" > /dev/null 2>&1 || { echo "Missing command: ${cmd}" && exit 1; }
+        done
+
+        # Check that the file exists before performing actions on it
+        if [ ! -s "$input_file" ]; then
+          echo "Diff file (git.diff) is missing or empty!"
+          exit 1
+        fi
+
+        # Reverse the file, remove 4 lines after '+++ /dev/null', then reverse it back (editors can't go backwards - to remove lines above)
+        tac "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
+        sed '/+++ \/dev\/null/{n;N;N;N;d;}' "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
+        tac "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
+
+        # Remove the lines between '+++ /dev/null' (included) and 'diff --git a/'
+        awk '
+          BEGIN { in_block=0 }
+          /\+\+\+ \/dev\/null/ { in_block=1; next }
+          in_block && /diff --git a\// { in_block=0; print; next }
+          !in_block
+        ' "$input_file" > "$temp_file"
+
+        # Check that the file exists before performing actions on it
+        if [ -s "$temp_file" ]; then
+          mv "$temp_file" "$input_file"
+          exit 0
+        fi
+
+        echo "Temp diff file (temp_diff_file.diff) is missing or empty!"
+        exit 1
 
     - name: Split diffs
       id: split_diffs
@@ -69,10 +88,16 @@ runs:
         # Check that the file exists before performing actions on it
         if [ ! -s git.diff ]; then
           echo "Diff file (git.diff) is missing or empty!"
+          exit 1
         fi
 
         # Make a file containing all the mutants for the differences in the PR and a folder to split them into big and small packages
         cargo mutants --in-diff git.diff --list > all_mutants.txt
+        if [ $? -ne 0 ]; then 
+          echo "Error retrieving the list of mutants!"
+          exit $?
+        fi
+
         mkdir -p mutants_by_packages
 
         # Check that the file exists before performing actions on it
@@ -114,7 +139,6 @@ runs:
         done
 
         exit 0
-      working-directory: actions-repo/mutation-testing/shell-scripts
 
     - name: Run mutants
       id: run_mutants
@@ -169,12 +193,10 @@ runs:
 
         # Enable immediate exit on error again
         set -e
-      working-directory: actions-repo/mutation-testing/shell-scripts
 
     - name: Upload artifact
       id: upload_artifact
-      uses: actions/upload-artifact@v3
-      if: always()
+      uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v4.1.0
       with:
         name: mutants-shard-${{ inputs.package-dimension }}-${{ inputs.shard }}
-        path: actions-repo/mutation-testing/shell-scripts/mutants-shard-${{ inputs.package-dimension }}-${{ inputs.shard }}
+        path: mutants-shard-${{ inputs.package-dimension }}-${{ inputs.shard }}
