fix: special case for stacks-signer

diff --git a/stacks-core/mutation-testing/pr-differences/action.yml b/stacks-core/mutation-testing/pr-differences/action.yml
--- a/stacks-core/mutation-testing/pr-differences/action.yml
+++ b/stacks-core/mutation-testing/pr-differences/action.yml
@@ -10,7 +10,7 @@ inputs:
     required: false
     default: -1
   package-dimension:
-    description: "The dimension of the package. `big` for `stacks-node` and `stackslib`, `small` for others"
+    description: "The dimension of the package. `big` for `stacks-node` and `stackslib`, `small` for others, `stacks-signer` for `stacks-signer`."
     required: true
 
 runs:
@@ -54,38 +54,48 @@ runs:
         input_file="git.diff"
         temp_file="temp_diff_file.diff"
 
-        # Check if the commands exist on the host
-        for cmd in tac awk sed; do
-          command -v "${cmd}" > /dev/null 2>&1 || { echo "Missing command: ${cmd}" && exit 1; }
-        done
-
-        # Check that the file exists before performing actions on it
+        # Check if the file exists and is not empty
         if [ ! -s "$input_file" ]; then
-          echo "Diff file (git.diff) is missing or empty!"
+          echo "Diff file ($input_file) is missing or empty!"
           exit 1
         fi
 
-        # Reverse the file, remove 4 lines after '+++ /dev/null', then reverse it back (editors can't go backwards - to remove lines above)
-        tac "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
-        sed '/+++ \/dev\/null/{n;N;N;N;d;}' "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
-        tac "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
-
-        # Remove the lines between '+++ /dev/null' (included) and 'diff --git a/'
+        # Remove all lines related to deleted files including the first 'diff --git' line
         awk '
-          BEGIN { in_block=0 }
-          /\+\+\+ \/dev\/null/ { in_block=1; next }
-          in_block && /diff --git a\// { in_block=0; print; next }
-          !in_block
-        ' "$input_file" > "$temp_file"
+          /^diff --git/ {
+            diff_line = $0
+            getline
+            if ($0 ~ /^deleted file mode/) {
+              in_deleted_file_block = 1
+            } else {
+              if (diff_line != "") {
+                print diff_line
+                diff_line = ""
+              }
+              in_deleted_file_block = 0
+            }
+          }
+          !in_deleted_file_block
+        ' "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
 
-        # Check that the file exists before performing actions on it
-        if [ -s "$temp_file" ]; then
-          mv "$temp_file" "$input_file"
-          exit 0
-        fi
-
-        echo "Temp diff file (temp_diff_file.diff) is missing or empty!"
-        exit 1
+        # Remove 'diff --git' lines only when followed by 'similarity index', 'rename from', and 'rename to'
+        awk '
+          /^diff --git/ {
+            diff_line = $0
+            getline
+            if ($0 ~ /^similarity index/) {
+              getline
+              if ($0 ~ /^rename from/) {
+                getline
+                if ($0 ~ /^rename to/) {
+                  next
+                }
+              }
+            }
+            print diff_line  
+          }
+          { print }
+        ' "$input_file" > "$temp_file" && mv "$temp_file" "$input_file"
 
     - name: Split diffs
       id: split_diffs
@@ -120,6 +130,9 @@ runs:
             "testnet" | "stackslib")
               echo "$line" >> "mutants_by_packages/big_packages.txt"
               ;;
+            "stacks-signer")
+              echo "$line" >> "mutants_by_packages/stacks_signer.txt"
+              ;;
             *)
               echo "$line" >> "mutants_by_packages/small_packages.txt"
               ;;
@@ -139,6 +152,8 @@ runs:
 
           if [[ "$package" == "mutants_by_packages/big_packages.txt" ]]; then
             echo "$regex_pattern" > mutants_by_packages/regex_big.txt
+          elif [[ "$package" == "mutants_by_packages/stacks_signer.txt" ]]; then
+            echo "$regex_pattern" > mutants_by_packages/regex_stacks_signer.txt
           else
             echo "$regex_pattern" > mutants_by_packages/regex_small.txt
           fi
@@ -159,6 +174,14 @@ runs:
             if [[ -f mutants_by_packages/regex_big.txt ]]; then
               echo "Running mutants without shards on big packages"
               cargo mutants --no-shuffle -vV -F "$(<mutants_by_packages/regex_big.txt)" -E ": replace .{1,2} with .{1,2} in " --output ./ --test-tool=nextest -- --all-targets --test-threads 1
+              exit_code=$?
+            else
+              echo "File containing mutants doesn't exist!"
+            fi
+          elif [[ ${{ inputs.package-dimension }} == stacks-signer ]]; then
+            if [[ -f mutants_by_packages/regex_stacks_signer.txt ]]; then
+              echo "Found mutants on stacks-signer package, running them"
+              cargo mutants --no-shuffle -vV -F "$(<mutants_by_packages/regex_stacks_signer.txt)" -E ": replace .{1,2} with .{1,2} in " --output ./ --test-tool=nextest -- --all-targets --test-threads 1
               exit_code=$?
             else
               echo "File containing mutants doesn't exist!"
