asdf

diff --git a/stacks-core/downstream-pr/action.yml b/stacks-core/downstream-pr/action.yml
--- a/stacks-core/downstream-pr/action.yml
+++ b/stacks-core/downstream-pr/action.yml
@@ -30,6 +30,7 @@ runs:
         TARGET_BRANCH=""
         COMMIT_HASH=$(git log -1 '--pretty=%H') # retrieve the branch commit hash (used to determine who to assign the PR to)
         EXIT_CODE=0
+        MSG=""
 
         ## set target branch depending on SOURCE_BRANCH
         case $SOURCE_BRANCH in
@@ -55,27 +56,30 @@ runs:
         echo "LINE 55 - run cmd: git ls-remote --exit-code --quiet --heads origin ${TARGET_BRANCH}"
         if ! git ls-remote --exit-code --quiet --heads origin ${TARGET_BRANCH}; then
             cat <<EOF >> $GITHUB_STEP_SUMMARY
-        Target Branch (\`${TARGET_BRANCH}\`) does not exist.
+        Target Branch \`${TARGET_BRANCH}\` does not exist.
         EOF
-        echo "LINE 60 - exiting 1"
+        echo "LINE 61 - exiting 1"
         exit 1
         fi
 
         ## Check diff of source with the target branch origin
-        echo "LINE 65 - running: git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet"
-        DIFF_1=$(git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
-        echo "LINE 67 - DIFF_1 exit code: $DIFF_1"
+        echo "LINE 66 - running: git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet"
+        BRANCH_DIFF=$(git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
+        echo "LINE 68 - BRANCH_DIFF exit code: $BRANCH_DIFF"
         # git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet
+        # 0 - no diff
+        # 1 - diff
+        # 128 - branch not found
 
 
-        echo "LINE 71 - running: git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet"
+        echo "LINE 75 - running: git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet"
         DIFF_2=$(git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
-        echo "LINE 73 - DIFF_2 exit code: $DIFF_2"
+        echo "LINE 77 - DIFF_2 exit code: $DIFF_2"
         # # git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet
 
-        echo "LINE 76 - Running: git diff --name-only origin/develop..origin/next --exit-code"
+        echo "LINE 80 - Running: git diff --name-only origin/develop..origin/next --exit-code"
         DIFF_3=$(git diff --name-only origin/${SOURCE_BRANCH}..origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
-        echo "LINE 78 - DIFF_3 exit code: $DIFF_3"
+        echo "LINE 82 - DIFF_3 exit code: $DIFF_3"
         # git diff --name-only origin/${SOURCE_BRANCH}..origin/${TARGET_BRANCH} --exit-code --quiet
 
         # # echo "LINE 77 - check diff"
@@ -84,63 +88,60 @@ runs:
         # BRANCH_DIFF=$(git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --quiet --exit-code > /dev/null 2&>1; echo $?)
         # echo "LINE 81 - BRANCH_DIFF: ${BRANCH_DIFF}"
 
-        git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH}
+        # git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH}
+        # exit 0
 
-        exit 0
-        ## if the diff return code is 0, no files have changed and we can exit successfully
-        if [ "${BRANCH_DIFF}" -ne "1" ]; then
-          echo "LINE 86 - branch_diff: ${BRANCH_DIFF} (!= 1)"
-          MSG=""
-          echo "branch_diff (${BRANCH_DIFF} != 1 - no PR should be created"
+        if [ "${BRANCH_DIFF}" -eq "1" ];then
+          echo "LINE 95 - getting last commit uid"
+          ## using the commit_hash, retrieve the username of the last commit to assign the PR
+          ASSIGNED=$(curl -sL \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/commits/${COMMIT_HASH}" | jq -r .author.login
+          )
+          echo "LINE 102 - ASSIGNED: $ASSIGNED"
+          ## Finally, create the PR
+          echo "LINE 104 - create the PR"
+          PR=$(
+            gh pr create \
+              --assignee "${ASSIGNED}" \
+              --head "${SOURCE_BRANCH}" \
+              --base "${TARGET_BRANCH}" \
+              --title "Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}" \
+              --body "Automatic PR to Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}"
+          )
+          PR_NUM=$(basename "$PR")
+          echo "LINE 1114 - PR_NUM=${PR_NUM}"
+          MSG="PR [$PR_NUM]($PR) created and assigned to [$ASSIGNED](https://github.com/${ASSIGNED})"
+        else
+          ## if the diff return code is not 1, no files have changed or some other issue
+          echo "LINE 118 - branch_diff (!=1): ${BRANCH_DIFF}"
+          echo "LINE 119 - no PR should be created"
           case $BRANCH_DIFF in
             0)
-              echo "LINE 91 - branch_diff:${BRANCH_DIFF} (0)"
+              echo "LINE 122 - branch_diff:${BRANCH_DIFF} (0)"
               MSG="No changes detected between \`${SOURCE_BRANCH}\`->\`${TARGET_BRANCH}\`"
-              echo "LINE 93 - No changes detected between ${SOURCE_BRANCH}..${TARGET_BRANCH}"
+              echo "LINE 124 - No changes detected between ${SOURCE_BRANCH}..${TARGET_BRANCH}"
               EXIT_CODE=1
               ;;
             128)
-              echo "LINE 97 - branch_diff:${BRANCH_DIFF} (128)"
-              MSG="Target branch (\`${TARGET_BRANCH}\`) not found"
-              echo "LINE 99 - Target branch (${TARGET_BRANCH}) not found"
+              echo "LINE 128 - branch_diff:${BRANCH_DIFF} (128)"
+              MSG="Target branch \`${TARGET_BRANCH}\` not found"
+              echo "LINE 130 - Target branch (${TARGET_BRANCH}) not found"
               EXIT_CODE=2
               ;;
             *)
-              echo "LINE 103 - branch_diff:${BRANCH_DIFF}"
+              echo "LINE 134 - branch_diff:${BRANCH_DIFF}"
               MSG="Unknown error code"
-              echo "LINE 105 - Unknown error code"
+              echo "LINE 136 - Unknown error code"
               EXIT_CODE=3
               ;;
           esac
         fi
 
-        # if [ "${BRANCH_DIFF}" -eq "1" ];then
-        #   echo "LINE 94 getting last commit uid"
-        #   ## using the commit_hash, retrieve the username of the last commit to assign the PR
-        #   ASSIGNED=$(curl -sL \
-        #     -H "Accept: application/vnd.github+json" \
-        #     -H "X-GitHub-Api-Version: 2022-11-28" \
-        #     "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/commits/${COMMIT_HASH}" | jq -r .author.login
-        #   )
-        #   echo "LINE 101 ASSIGNED: $ASSIGNED"
-        #   ## Finally, create the PR
-        #   echo "LINE 103 create the PR"
-        #   PR=$(
-        #     gh pr create \
-        #       --assignee "${ASSIGNED}" \
-        #       --head "${SOURCE_BRANCH}" \
-        #       --base "${TARGET_BRANCH}" \
-        #       --title "Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}" \
-        #       --body "Automatic PR to Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}"
-        #   )
-        #   echo "LINE 112"
-        #   PR_NUM=$(basename "$PR")
-        #   echo "LINE 114 PR_NUM=${PR_NUM}"
-        #   MSG="PR [$PR_NUM]($PR) created and assigned to [$ASSIGNED](https://github.com/${ASSIGNED})"
-        # fi
         # cat <<EOF >> $GITHUB_STEP_SUMMARY
         # $MSG
         # EOF
-        echo "LINE 138 - MSG: $MSG"
-        echo "LINE 139 - exiting $EXIT_CODE"
+        echo "LINE 145 - MSG: $MSG"
+        echo "LINE 146 - exiting $EXIT_CODE"
         exit $EXIT_CODE
