asdf

diff --git a/stacks-core/downstream-pr/action.yml b/stacks-core/downstream-pr/action.yml
--- a/stacks-core/downstream-pr/action.yml
+++ b/stacks-core/downstream-pr/action.yml
@@ -64,23 +64,25 @@ runs:
         fi
         git fetch origin ${TARGET_BRANCH}
         ## Check diff of source with the target branch origin
-        echo "LINE 66 - running: git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet"
-        BRANCH_DIFF=$(git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
+        # echo "LINE 66 - running: git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet"
+        # BRANCH_DIFF=$(git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
+        echo "LINE 66 - running: git diff --name-only origin/${TARGET_BRANCH}..HEAD --exit-code --quiet"
+        BRANCH_DIFF=$(git diff --name-only origin/${TARGET_BRANCH}..HEAD --exit-code --quiet > /dev/null 2&>1; echo $?)
         echo "LINE 68 - BRANCH_DIFF exit code: $BRANCH_DIFF"
         # git diff --name-only origin/${TARGET_BRANCH} --exit-code --quiet
         # 0 - no diff
         # 1 - diff
         # 128 - branch not found
 
-        echo "LINE 75 - running: git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet"
-        DIFF_2=$(git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
-        echo "LINE 77 - DIFF_2 exit code: $DIFF_2"
-        # # git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet
+        # echo "LINE 75 - running: git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet"
+        # DIFF_2=$(git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet > /dev/null 2&>1; echo $?)
+        # echo "LINE 77 - DIFF_2 exit code: $DIFF_2"
+        # # # git diff --name-only origin/${SOURCE_BRANCH} origin/${TARGET_BRANCH} --exit-code --quiet
 
-        echo "LINE 80 - Running: git diff --name-only origin/${TARGET_BRANCH}..HEAD --exit-code"
-        DIFF_3=$(git diff --name-only origin/${TARGET_BRANCH}..HEAD --exit-code --quiet > /dev/null 2&>1; echo $?)
-        echo "LINE 82 - DIFF_3 exit code: $DIFF_3"
-        # git diff --name-only origin/${SOURCE_BRANCH}..origin/${TARGET_BRANCH} --exit-code --quiet
+        # echo "LINE 80 - Running: git diff --name-only origin/${TARGET_BRANCH}..HEAD --exit-code"
+        # DIFF_3=$(git diff --name-only origin/${TARGET_BRANCH}..HEAD --exit-code --quiet > /dev/null 2&>1; echo $?)
+        # echo "LINE 82 - DIFF_3 exit code: $DIFF_3"
+        # # git diff --name-only origin/${SOURCE_BRANCH}..origin/${TARGET_BRANCH} --exit-code --quiet
 
         # # echo "LINE 77 - check diff"
         # echo "LINE 78 - run cmd: git diff --name-only origin/${TARGET_BRANCH} --quiet --exit-code > /dev/null 2&>1; echo \$?"
