asdf

diff --git a/stacks-core/downstream-pr/action.yml b/stacks-core/downstream-pr/action.yml
--- a/stacks-core/downstream-pr/action.yml
+++ b/stacks-core/downstream-pr/action.yml
@@ -18,12 +18,9 @@ runs:
       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         fetch-depth: 0
-
-    - name: Create PR
-      id: create-pr
+    - name: Set Variables
+      id: set-vars
       shell: bash
-      env:
-        GH_TOKEN: ${{ inputs.token }}
       run: |
 
         SOURCE_BRANCH=${{ github.ref_name }} # use the source branch that called this workflow
@@ -48,7 +45,8 @@ runs:
         DIFF_RET="$?"
         ## if the diff return code is 0, no files have changed and we can exit successfully
         if [ "${DIFF_RET}" -eq "0" ];then
-          echo "No diff - skipping PR creation"
+          echo "No changes detected between ${SOURCE_BRANCH}->${TARGET_BRANCH}"
+          echo "  Skipping PR creation"
           exit 0
         fi
 
@@ -58,11 +56,56 @@ runs:
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/commits/${COMMIT_HASH}" | jq -r .author.login
         )
+        echo "SOURCE_BRANCH=${SOURCE_BRANCH}" >> "$GITHUB_OUTPUT"
+        echo "TARGET_BRANCH=${TARGET_BRANCH}" >> "$GITHUB_OUTPUT"
+        echo "COMMIT_HASH=${COMMIT_HASH}" >> "$GITHUB_OUTPUT"
+        echo "ASSIGNED=${ASSIGNED}" >> "$GITHUB_OUTPUT"
 
+    - name: Create PR
+      id: create-pr
+      shell: bash
+      env:
+        GH_TOKEN: ${{ inputs.token }}
+      run: |
+
+        # SOURCE_BRANCH=${{ github.ref_name }} # use the source branch that called this workflow
+        # TARGET_BRANCH=""
+        # COMMIT_HASH=$(git log -1 '--pretty=%H') # retrieve the branch commit hash (used to determine who to assign the PR to)
+
+        # ## set target branch depending on SOURCE_BRANCH
+        # case $SOURCE_BRANCH in
+        #   develop)
+        #     TARGET_BRANCH="next"
+        #     ;;
+        #   master)
+        #     TARGET_BRANCH="develop"
+        #     ;;
+        #   *)
+        #     exit 1
+        #     ;;
+        # esac
+
+        # ## Check diff of source with the target branch origin
+        # $(git diff origin/${TARGET_BRANCH} --quiet --exit-code)
+        # DIFF_RET="$?"
+        # ## if the diff return code is 0, no files have changed and we can exit successfully
+        # if [ "${DIFF_RET}" -eq "0" ];then
+        #   echo "No diff - skipping PR creation"
+        #   exit 0
+        # fi
+
+        # ## using the commit_hash, retrieve the username of the last commit to assign the PR
+        # ASSIGNED=$(curl -sL \
+        #   -H "Accept: application/vnd.github+json" \
+        #   -H "X-GitHub-Api-Version: 2022-11-28" \
+        #   "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/commits/${COMMIT_HASH}" | jq -r .author.login
+        # )
+
+        echo "conclusion: ${{ steps.set-vars.conclusion }}"
         ## Finally, create the PR
         gh pr create \
-          --assignee "${ASSIGNED}" \
-          --head "${SOURCE_BRANCH}" \
-          --base "${TARGET_BRANCH}" \
-          --title "Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}" \
-          --body "Automatic PR to Merge ${SOURCE_BRANCH} to ${TARGET_BRANCH}"
+          --assignee "${{ env.ASSIGNED }}" \
+          --head "${{ env.SOURCE_BRANCH }}" \
+          --base "${{ env.TARGET_BRANCH }}" \
+          --title "Merge ${{ env.SOURCE_BRANCH }} to ${ env.{TARGET_BRANCH }}" \
+          --body "Automatic PR to Merge ${{ env.SOURCE_BRANCH }} to ${{ env.TARGET_BRANCH }}"
