feat: update actions version, add comments, check files before accessing them

diff --git a/mutation-testing/pr-differences/action.yml b/mutation-testing/pr-differences/action.yml
--- a/mutation-testing/pr-differences/action.yml
+++ b/mutation-testing/pr-differences/action.yml
@@ -21,7 +21,7 @@ runs:
     # Checkout the stacks-core code
     - name: Checkout the stacks core repo
       id: git_checkout_stacks_core
-      uses: actions/checkout@v3
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         fetch-depth: 0
 
@@ -33,7 +33,7 @@ runs:
     # Checkout the actions code
     - name: Get the action repo code
       id: git_checkout_actions
-      uses: actions/checkout@v3
+      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         repository: stacks-network/actions
         ref: feat/mutation-testing
@@ -42,11 +42,16 @@ runs:
     - name: Copy the git diff file to scripts folder
       shell: bash
       run: |
+        if [ ! -s git.diff ]; then
+          echo "Diff file missing!"
+        fi
+
         mv git.diff ./actions-repo/mutation-testing/shell-scripts/
 
-    - name: Install cargo mutants crate
-      shell: bash
-      run: cargo install --version 23.12.2 cargo-mutants
+    - uses: taiki-e/install-action@ac89944b5b150d78567ab6c02badfbe48b0b55aa # v2.20.16
+      name: Install cargo-mutants
+      with:
+        tool: cargo-mutants@23.12.2 # v23.12.2
 
     - name: Remove deleted file lines from git.diff file
       shell: bash
@@ -56,42 +61,64 @@ runs:
     - name: Split diffs into big and small packages and create regex patterns for them
       shell: bash
       run: |
+        # Check that the file exists before performing actions on it
+        if [ ! -s git.diff ]; then
+          echo "Diff file missing!"
+        fi
+
+        # Make a file containing all the mutants for the differences in the PR and a folder to split them into big and small packages
         cargo mutants --in-diff git.diff --list > all_mutants.txt
         mkdir -p mutants_by_packages
+
+        # Check that the file exists before performing actions on it
+        if [ ! -s all_mutants.txt ]; then
+          echo "The file containing mutants is missing or empty!"
+          exit 1
+        fi
 
         # Split the differences from git into 2 parts, big packages ('stacks-node' and 'stackslib') and small packages (all others) and put them into separate files
         while IFS= read -r line; do
           package=$(echo "$line" | cut -d'/' -f1)
-          if [[ $package == "testnet" || $package == "stackslib" ]]; then
-            echo "$line" >> "mutants_by_packages/big_packages.txt"
-          else
-            echo "$line" >> "mutants_by_packages/small_packages.txt"
-          fi
+          ccase $package in
+            "testnet" | "stackslib")
+              echo "$line" >> "mutants_by_packages/big_packages.txt"
+              ;;
+            *)
+              echo "$line" >> "mutants_by_packages/small_packages.txt"
+              ;;
+          esac
         done < all_mutants.txt
 
         # Create regex patterns of the mutants to be ran for `cargo mutants` -F flag and output them to files to be used later
         for package in mutants_by_packages/*; do
-          regex_pattern=""
+          if [ -s mutants_by_packages/$package ]; then
+            regex_pattern=""
 
-          while IFS= read -r line; do
-            escaped_line=$(echo "$line" | sed 's/[][()\.^$*+?{}|]/\\&/g')
-            regex_pattern+="($escaped_line)|"
-          done < "$package"
+            while IFS= read -r line; do
+              escaped_line=$(echo "$line" | sed 's/[][()\.^$*+?{}|]/\\&/g')
+              regex_pattern+="($escaped_line)|"
+            done < "$package"
 
-          regex_pattern="${regex_pattern%|}"
+            regex_pattern="${regex_pattern%|}"
 
-          if [[ "$package" == "mutants_by_packages/big_packages.txt" ]]; then
-            echo "$regex_pattern" > mutants_by_packages/regex_big.txt
-          else
-            echo "$regex_pattern" > mutants_by_packages/regex_small.txt
+            if [[ "$package" == "mutants_by_packages/big_packages.txt" ]]; then
+              echo "$regex_pattern" > mutants_by_packages/regex_big.txt
+            else
+              echo "$regex_pattern" > mutants_by_packages/regex_small.txt
+            fi
           fi
         done
+
+        exit 0
       working-directory: actions-repo/mutation-testing/shell-scripts
 
     - name: Run mutants and check the exit code of the command, fail the workflow if mutations are not caught
       shell: bash
       run: |
-        set +e  # Disable immediate exit on error
+        # Disable immediate exit on error
+        set +e
+
+        # Check which type of mutants to run: big, small, with or without shards, then capture the exit code
         if [[ ${{ inputs.shard }} == -1 ]]; then
           if [[ ${{ inputs.package-dimension }} == big ]]; then
             echo "Running mutants without shards on big packages"
@@ -113,10 +140,14 @@ runs:
             exit_code=$?
           fi
         fi
+
+        # Create the folder only containing the outcomes (.txt files) and make a file containing the exit code of the command
         mkdir mutants-shard-${{ inputs.package-dimension }}-${{ inputs.shard }}
         echo "$exit_code" > ./mutants-shard-${{ inputs.package-dimension }}-${{ inputs.shard }}/exit_code.txt
         mv ./mutants.out/*.txt mutants-shard-${{ inputs.package-dimension }}-${{ inputs.shard }}/
-        set -e  # Enable immediate exit on error again
+
+        # Enable immediate exit on error again
+        set -e
       working-directory: actions-repo/mutation-testing/shell-scripts
 
     - name: Upload artifact
