feat: exit if generated checksum variable is empty, update readme

diff --git a/generate-checksum/action.yml b/generate-checksum/action.yml
--- a/generate-checksum/action.yml
+++ b/generate-checksum/action.yml
@@ -23,12 +23,19 @@ runs:
       id: generate_checksum
       shell: bash
       run: |
+        # If sha512sum command doesn't exist on the host, exit
         if ! command -v sha512sum > /dev/null 2>&1; then
           echo "sha512sum command doesn't exist!";
           exit 1;
         fi
 
+        # Generate the hashes and exit if the variable is empty
         shasum="$(sha512sum release/*)"
+        if [[ -z "$shasum" ]]; then
+          echo "Checksum could not be generated!";
+          exit 1;
+        fi
+
         echo "Generated checksums:"
         echo "$shasum"
         echo "$shasum" > "${{ inputs.hashfile_name }}";
